from os import getenv

POSTGRES_DB=getenv("POSTGRES_DB")
POSTGRES_HOST=getenv("POSTGRES_HOST")
POSTGRES_PORT=getenv("POSTGRES_PORT")
POSTGRES_SCHEMA=getenv("POSTGRES_SCHEMA")

APP_DB_USER=getenv("APP_DB_USER")
APP_DB_PASS=getenv("APP_DB_PASS")
